export type DrawingStatus = "draft" | "for_review" | "issued" | "revise_resubmit";

export type Drawing = {
  id: string;
  projectId: string;
  sheetNumber: string;
  title: string;
  discipline: "Architectural" | "Structural" | "MEP" | "Landscape" | "Interiors";
  revision: string;
  status: DrawingStatus;
  lastIssuedDate: string;
};

export const DRAWING_STATUS_META: Record<
  DrawingStatus,
  { label: string; pill: "good" | "warning" | "critical" | "neutral" }
> = {
  draft: { label: "Draft", pill: "neutral" },
  for_review: { label: "For Review", pill: "warning" },
  issued: { label: "Issued", pill: "good" },
  revise_resubmit: { label: "Revise & Resubmit", pill: "critical" },
};

export const DRAWINGS: Drawing[] = [
  {
    id: "dwg-01",
    projectId: "marina-tower",
    sheetNumber: "A-101",
    title: "Ground Floor Plan",
    discipline: "Architectural",
    revision: "Rev C",
    status: "issued",
    lastIssuedDate: "2026-07-02",
  },
  {
    id: "dwg-02",
    projectId: "marina-tower",
    sheetNumber: "A-501",
    title: "Facade Elevations — North & South",
    discipline: "Architectural",
    revision: "Rev D",
    status: "for_review",
    lastIssuedDate: "2026-07-09",
  },
  {
    id: "dwg-03",
    projectId: "marina-tower",
    sheetNumber: "A-601",
    title: "Curtain Wall Details",
    discipline: "Architectural",
    revision: "Rev B",
    status: "draft",
    lastIssuedDate: "2026-06-24",
  },
  {
    id: "dwg-04",
    projectId: "greenfield-campus",
    sheetNumber: "S-101",
    title: "Foundation Plan",
    discipline: "Structural",
    revision: "Rev F",
    status: "issued",
    lastIssuedDate: "2026-06-18",
  },
  {
    id: "dwg-05",
    projectId: "greenfield-campus",
    sheetNumber: "A-901",
    title: "Reflected Ceiling Plan — Library Wing",
    discipline: "Architectural",
    revision: "Rev C",
    status: "revise_resubmit",
    lastIssuedDate: "2026-07-08",
  },
  {
    id: "dwg-06",
    projectId: "greenfield-campus",
    sheetNumber: "M-301",
    title: "MEP Coordination Plan — Level 2",
    discipline: "MEP",
    revision: "Rev E",
    status: "for_review",
    lastIssuedDate: "2026-07-11",
  },
  {
    id: "dwg-07",
    projectId: "al-noor-residences",
    sheetNumber: "A-201",
    title: "Typical Unit Plans",
    discipline: "Architectural",
    revision: "Rev B",
    status: "draft",
    lastIssuedDate: "2026-07-01",
  },
  {
    id: "dwg-08",
    projectId: "al-noor-residences",
    sheetNumber: "A-301",
    title: "Building Sections",
    discipline: "Architectural",
    revision: "Rev A",
    status: "for_review",
    lastIssuedDate: "2026-07-07",
  },
  {
    id: "dwg-09",
    projectId: "harbor-view-offices",
    sheetNumber: "A-101",
    title: "Ground Floor Plan",
    discipline: "Architectural",
    revision: "Rev G",
    status: "issued",
    lastIssuedDate: "2026-06-15",
  },
  {
    id: "dwg-10",
    projectId: "harbor-view-offices",
    sheetNumber: "S-201",
    title: "Structural Framing Plan — Level 5",
    discipline: "Structural",
    revision: "Rev D",
    status: "issued",
    lastIssuedDate: "2026-06-20",
  },
  {
    id: "dwg-11",
    projectId: "falcon-retail-fitout",
    sheetNumber: "A-001",
    title: "Concept Floor Plan",
    discipline: "Architectural",
    revision: "Rev A",
    status: "draft",
    lastIssuedDate: "2026-07-05",
  },
  {
    id: "dwg-12",
    projectId: "desert-oasis-resort",
    sheetNumber: "L-101",
    title: "Landscape Hardscape Plan",
    discipline: "Landscape",
    revision: "Rev B",
    status: "for_review",
    lastIssuedDate: "2026-07-10",
  },
  {
    id: "dwg-13",
    projectId: "desert-oasis-resort",
    sheetNumber: "A-401",
    title: "Villa Type Elevations",
    discipline: "Architectural",
    revision: "Rev A",
    status: "draft",
    lastIssuedDate: "2026-06-27",
  },
  {
    id: "dwg-14",
    projectId: "central-library",
    sheetNumber: "A-001",
    title: "Existing Conditions Survey",
    discipline: "Architectural",
    revision: "Rev A",
    status: "issued",
    lastIssuedDate: "2026-06-12",
  },
  {
    id: "dwg-15",
    projectId: "central-library",
    sheetNumber: "A-101",
    title: "Concept Floor Plan",
    discipline: "Architectural",
    revision: "Rev B",
    status: "draft",
    lastIssuedDate: "2026-07-03",
  },
  {
    id: "dwg-16",
    projectId: "seaside-villas",
    sheetNumber: "A-101",
    title: "Ground Floor Plan — CD Set",
    discipline: "Architectural",
    revision: "Rev B",
    status: "issued",
    lastIssuedDate: "2026-07-06",
  },
  {
    id: "dwg-17",
    projectId: "seaside-villas",
    sheetNumber: "A-501",
    title: "Roof Plan",
    discipline: "Architectural",
    revision: "Rev B",
    status: "for_review",
    lastIssuedDate: "2026-07-11",
  },
  {
    id: "dwg-18",
    projectId: "seaside-villas",
    sheetNumber: "ID-401",
    title: "Interior Finishes Schedule",
    discipline: "Interiors",
    revision: "Rev A",
    status: "draft",
    lastIssuedDate: "2026-06-30",
  },
];
