// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations need a direct (non-pooled) connection: Neon's pooler runs
    // PgBouncer in transaction mode, which breaks the session-scoped advisory
    // lock `prisma migrate deploy` uses (P1002 timeout). The app itself keeps
    // using the pooled DATABASE_URL at runtime via the driver adapter in
    // src/lib/db.ts — only this CLI-facing config needs the direct URL.
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
